name: deskmate
description: AI Study Companion that helps students stay focused, organized, and productive.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  camera: ^0.10.5+2
  path_provider: ^2.1.0
  audioplayers: ^5.2.1
  speech_to_text: ^6.3.0
  flutter_blue_plus: ^1.14.7
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/placeholder.svg
    - assets/icons/app_icon.svg
